// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYCTq-Yipm5BEj2-l0Dje0-_qvtI8DQ4A',
    appId: '1:333355870766:web:15215f193133e87b820dbf',
    messagingSenderId: '333355870766',
    projectId: 'mobprota',
    authDomain: 'mobprota.firebaseapp.com',
    storageBucket: 'mobprota.appspot.com',
    measurementId: 'G-LG3Q14JRVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrmYpIhyubz6v34hMdmxxJCbFJSdw9UpA',
    appId: '1:333355870766:android:fa46b3d325093679820dbf',
    messagingSenderId: '333355870766',
    projectId: 'mobprota',
    storageBucket: 'mobprota.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM5xcX9hiMWNqILXKvmP3pR7TGbRQEAwg',
    appId: '1:333355870766:ios:7c597e66018873a9820dbf',
    messagingSenderId: '333355870766',
    projectId: 'mobprota',
    storageBucket: 'mobprota.appspot.com',
    iosClientId: '333355870766-fjfvtu4m06vpads48ds1j28rk88gm1sc.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );
}
